import { upsertNode } from '@/api/canvas';

import { AUTO_GENERATED_PLACEHOLDER_PATTERN } from './nodeLabels';

import type { Node } from '@xyflow/react';

export type NodeIngestionStatus = 'pending' | 'success' | 'error';

export type NodeIngestionInfo = {
  status: NodeIngestionStatus;
  updatedAt: number;
  error?: string;
};

export type IngestHelperDeps = {
  canvasId: string;
  node: Node;

  setNodeIngestion: (nodeId: string, info: NodeIngestionInfo) => void;
  clearNodeIngestion: (nodeId: string) => void;
  getNodeById: (nodeId: string) => Node | undefined;
  /** Silently patch node data without recording undo history. */
  patchNodeSilent: (nodeId: string, patch: Record<string, unknown>) => void;
};

export function needsIngestion(nodeType: string): boolean {
  return ['note', 'text', 'web', 'pdf'].includes(nodeType);
}

function getStringDataField(node: Node, field: string): string {
  const data = node.data as Record<string, unknown> | undefined;
  const value = data?.[field];
  return typeof value === 'string' ? value : '';
}

/**
 * Decide whether a node update should trigger ingestion.
 * Key fields:
 * - note/text: content
 * - web/pdf: src
 */
export function shouldIngestOnUpdate(prevNode: Node, nextNode: Node): boolean {
  const nextType = nextNode.type ?? '';
  if (!needsIngestion(nextType)) return false;

  if ((prevNode.type ?? '') !== nextType) return true;

  if (nextType === 'note' || nextType === 'text') {
    // `content` is the canonical Markdown — re-ingest whenever it changes.
    return (
      getStringDataField(prevNode, 'content') !==
      getStringDataField(nextNode, 'content')
    );
  }

  if (nextType === 'web' || nextType === 'pdf') {
    return (
      getStringDataField(prevNode, 'src') !==
      getStringDataField(nextNode, 'src')
    );
  }

  return false;
}

export async function ingestNodeIfNeeded({
  canvasId,
  node,
  setNodeIngestion,
  clearNodeIngestion,
  getNodeById,
  patchNodeSilent,
}: IngestHelperDeps): Promise<void> {
  if (!needsIngestion(node.type ?? '')) return;

  setNodeIngestion(node.id, {
    status: 'pending',
    updatedAt: Date.now(),
  });

  const nodeData = node.data as Record<string, unknown> | undefined;

  try {
    // Prepare title for backend - skip auto-generated placeholders
    const currentLabel = (nodeData?.label as string) || '';
    const isAutoGeneratedPlaceholder =
      AUTO_GENERATED_PLACEHOLDER_PATTERN.test(currentLabel);

    // Only send title if it's not a placeholder
    const titleToSend = isAutoGeneratedPlaceholder
      ? undefined
      : currentLabel || (nodeData?.title as string) || undefined;

    // `content` is always Markdown (the canonical representation), so we
    // can send it directly to all storage backends including Obsidian.
    const nodeType = node.type as string;

    const response = await upsertNode(canvasId, node.id, {
      type: nodeType as 'note' | 'text' | 'web' | 'pdf',
      title: titleToSend,
      content: (nodeData?.content as string) || undefined,
      src: (nodeData?.src as string) || undefined,
      sourceId: (nodeData?.sourceId as string) || undefined,
    });

    if (response.sourceId) {
      patchNodeSilent(node.id, { sourceId: response.sourceId });
    }

    // Optionally apply server-suggested label (e.g. parsed PDF/web title).
    // Overwrite if current label is empty OR is an auto-generated placeholder.
    if (response.success && response.suggestedLabel) {
      const suggestedLabel = response.suggestedLabel.trim();

      if (suggestedLabel.length > 0) {
        const currentNode = getNodeById(node.id);
        if (currentNode) {
          const currentLabel =
            typeof (currentNode.data as Record<string, unknown> | undefined)
              ?.label === 'string'
              ? ((currentNode.data as Record<string, unknown>).label as string)
              : '';

          const isEmptyLabel = currentLabel.trim().length === 0;

          // Check if current label is an auto-generated placeholder
          const isAutoGeneratedPlaceholder =
            AUTO_GENERATED_PLACEHOLDER_PATTERN.test(currentLabel);

          if (isEmptyLabel || isAutoGeneratedPlaceholder) {
            // Do not re-trigger ingestion when applying server-suggested metadata.
            patchNodeSilent(node.id, { label: suggestedLabel });
          }
        }
      }
    }

    if (response.success) {
      // Keep the ingestion map small; UI only needs pending.
      clearNodeIngestion(node.id);
      return;
    }

    // EMPTY_CONTENT is expected for newly created note/text nodes – not a real error.
    const isExpectedEmpty = response.error?.includes('EMPTY_CONTENT');

    if (isExpectedEmpty) {
      clearNodeIngestion(node.id);
      return;
    }

    setNodeIngestion(node.id, {
      status: 'error',
      updatedAt: Date.now(),
      error: response.error ?? 'Unknown ingestion error',
    });

    console.error(
      'Node ingestion did not complete successfully:',
      node.id,
      response.error,
    );
  } catch (error) {
    setNodeIngestion(node.id, {
      status: 'error',
      updatedAt: Date.now(),
      error: error instanceof Error ? error.message : String(error),
    });
    console.error('Failed to ingest node:', node.id, error);
  }
}
