import { Handle, Position, NodeResizer, NodeToolbar } from '@xyflow/react';
import { clsx } from 'clsx';
import { GripVertical } from 'lucide-react';
import React, { memo, useCallback } from 'react';

import useCanvasStore from '@/store/canvasStore.ts';

import type { CanvasNodeType, NodeData } from './types.ts';

interface NodeWrapperProps {
  id: string;
  data: NodeData;
  type: CanvasNodeType;
  selected?: boolean;

  allowOverflow?: boolean;

  children: React.ReactNode;
  className?: string;
  minWidth?: number;
  minHeight?: number;
  toolbar?: React.ReactNode;

  keepAspectRatio?: boolean;
  resizable?: boolean;

  onResizeStart?: () => void;
  onResize?: (width: number, height: number) => void;
  onResizeEnd?: (width: number, height: number) => void;
  onDoubleClick?: React.MouseEventHandler<HTMLDivElement>;
}

export const NodeWrapper = memo(
  ({
    id,
    type,
    data,
    selected,
    children,
    className,
    minWidth,
    minHeight,
    toolbar,
    keepAspectRatio = false,
    resizable = true,

    allowOverflow = false,

    onResizeStart,
    onResize: onResizeProp,
    onResizeEnd,
    onDoubleClick,
  }: NodeWrapperProps) => {
    const selectedCount = useCanvasStore(
      (state) => state.nodes.filter((node) => node.selected).length,
    );

    const ingestion = useCanvasStore((state) => state.ingestionByNodeId[id]);
    const showIngestionOverlay =
      type !== 'frame' && ingestion?.status === 'pending';

    // Check if this node was generated by research
    const isResearchGenerated = data.origin === 'research';

    const handleResize = useCallback(
      (_event: unknown, params: { width: number; height: number }) => {
        useCanvasStore.setState((state) => ({
          nodes: state.nodes.map((n) =>
            n.id === id
              ? {
                  ...n,
                  style: {
                    ...n.style,
                    width: params.width,
                    height: params.height,
                  },
                }
              : n,
          ),
        }));
        onResizeProp?.(params.width, params.height);
      },
      [id, onResizeProp],
    );

    const handleResizeStart = useCallback(() => {
      onResizeStart?.();
    }, [onResizeStart]);

    const handleResizeEnd = useCallback(
      (_event: unknown, params: { width: number; height: number }) => {
        onResizeEnd?.(params.width, params.height);
      },
      [onResizeEnd],
    );

    return (
      <>
        <NodeResizer
          color="#e6e6e6"
          isVisible={selected && resizable}
          minWidth={
            type === 'pdf' || type === 'note' || type === 'web' ? 120 : minWidth
          }
          minHeight={
            type === 'pdf' || type === 'note' || type === 'web'
              ? 120
              : minHeight
          }
          keepAspectRatio={keepAspectRatio}
          onResizeStart={handleResizeStart}
          onResize={handleResize}
          onResizeEnd={handleResizeEnd}
        />
        {type !== 'frame' && (
          <NodeToolbar
            isVisible={selected && selectedCount === 1}
            position={Position.Top}
            offset={12}
            className="border-border shadow-bottom flex h-8 items-center gap-3 rounded-md border bg-white px-2 py-1"
          >
            {toolbar}
          </NodeToolbar>
        )}

        <div
          className={clsx(
            'group relative flex h-full w-full flex-col rounded shadow transition-all duration-120',
            'style' in data && data.style?.backgroundColor
              ? data.style.backgroundColor
              : 'bg-transparent',
            selected ? 'ring-theme-500 ring' : 'ring-border hover:ring',
            // Research node visual identifier: left purple border
            isResearchGenerated && 'border-l-4 border-l-purple-500',
            className,
          )}
          onDoubleClick={onDoubleClick}
        >
          {showIngestionOverlay && (
            <div className="bg-background/40 pointer-events-none absolute inset-0 z-10 flex items-center justify-center">
              <div className="border-muted-foreground/30 border-t-muted-foreground h-5 w-5 animate-spin rounded-full border-2" />
            </div>
          )}

          <div
            className={clsx(
              'text-icon hover:text-main absolute top-0 -left-4.5 flex h-6 w-4 cursor-grab items-center justify-center rounded opacity-0 transition-opacity',
              'group-hover:opacity-100',
            )}
            draggable
            onDragStart={(e) => {
              e.dataTransfer.setData('application/json', JSON.stringify(data));
              e.dataTransfer.effectAllowed = 'copyMove';
            }}
          >
            <GripVertical size={16} />
          </div>

          <div
            className={clsx(
              'flex-1 p-0',
              allowOverflow ? 'overflow-visible' : 'overflow-hidden',
            )}
          >
            {children}
          </div>

          <Handle
            type="target"
            id="top-target"
            position={Position.Top}
            className="bg-theme-500! -top-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="source"
            id="top-source"
            position={Position.Top}
            className="bg-theme-500! -top-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="target"
            id="right-target"
            position={Position.Right}
            className="bg-theme-500! -right-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="source"
            id="right-source"
            position={Position.Right}
            className="bg-theme-500! -right-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="target"
            id="bottom-target"
            position={Position.Bottom}
            className="bg-theme-500! -bottom-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="source"
            id="bottom-source"
            position={Position.Bottom}
            className="bg-theme-500! -bottom-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="target"
            id="left-target"
            position={Position.Left}
            className="bg-theme-500! -left-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
          <Handle
            type="source"
            id="left-source"
            position={Position.Left}
            className="bg-theme-500! -left-1! h-1! w-1! border-none! opacity-0 transition-opacity group-hover:opacity-100"
          />
        </div>
      </>
    );
  },
);
